#!/bin/bash
if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 
   exit 1
fi

# Display Usage (if error or --help)
function usage () {
  echo "Usage: $0 [options] <values>"
  echo
  echo "Available Options:"
  echo " -i --install : Install package"
  echo "    Ex: $0 --install <package-name>"
  echo " -ppa --add-ppa : Add ppa"
  echo "    Ex: $0 --add-ppa <user> <ppa-name>" 
  echo " --ppa-install : Install from ppa"
  echo "    Ex: $0 --ppa-install <user> <ppa-name> <package-name>"
  echo " -r --remove : Remove package"
  echo "    Ex: $0 --remove <package-name>"
  echo " -rppa --remove-ppa : Remove PPA"
  echo "    Ex: $0 --remove-ppa <user> <ppa-name>"
  echo " -pdr --ppa-direct-remove"
  echo "    Ex: $0 --ppa-direct-remove <user> <ppa-name> <package-name>"
  echo " -src --add-custom-source : Adds Custom Package URL"
  echo "    Ex: $0 --add-custom-source <url>"
}

# Functionality
if [[ -z $1 ]]; then
    usage
else
    if [[ $1 = "--help" || $1 = "-h" ]]; then
        usage
    elif [[ $1 = "-i" || $1 = "--install" ]]; then
        apt-update
        apt install $2 -y
    elif [[ $1 = "-ppa" || $1 = "--add-ppa" ]]; then
        add-apt-repository ppa:$2/$3
        apt update
    elif [[ $1 = "--ppa-install" ]]; then
        add-apt-repository ppa:$2/$3
        apt update
        apt install $4
    elif [[ $1 = "-r" || $1 = "--remove" ]]; then
        apt remove $2
        apt update
    elif [[ $1 = "-rppa" || $1 = "--remove-ppa" ]]; then
        add-apt-repository --remove ppa:$2/$3
    elif [[ $1 = "-pdr" || $1 = "--ppa-direct-remove" ]]; then
        apt remove $4
        add-apt-repository --remove ppa:$2/$3
        apt update
    fi
fi